import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { createRequire } from 'node:module'
import { readFile, readdir } from 'node:fs/promises'
import { resolve } from 'node:path'

const requireModule = createRequire(import.meta.url)
const Ajv2020 = requireModule('@fastify/ajv-compiler/node_modules/ajv/dist/2020').default
const repoRoot = resolve(process.cwd(), '..')
const STAGES = ['A0', 'FTR-1', 'FTR-2', 'FTR-3', 'FTR-4', 'FTR-5']

function sha256Bytes(value: Buffer | string) {
  return createHash('sha256').update(value).digest('hex')
}

async function readJson(path: string) {
  return JSON.parse(await readFile(path, 'utf8'))
}

async function latestAuditDir() {
  if (process.env.FTR6_AUDIT_DIR) return resolve(process.env.FTR6_AUDIT_DIR)
  const root = resolve(process.cwd(), 'data/gpt-audit/formal-release-readiness/FTR-6')
  const entries = await readdir(root, { withFileTypes: true })
  for (const name of entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name).sort().reverse()) {
    const dir = resolve(root, name)
    try {
      const manifest = await readJson(resolve(dir, 'formal_release_review_manifest.json'))
      if (manifest.schemaVersion === 'fams.formal_release.provisional_review_manifest.v2') return dir
    } catch {
      // Ignore incomplete runs.
    }
  }
  throw new Error('ftr6_provisional_review_package_not_found')
}

async function validateSchema(schemaName: string, value: unknown) {
  const schema = await readJson(resolve(repoRoot, 'docs/contracts', schemaName))
  const ajv = new Ajv2020({ allErrors: true, strict: true, strictTypes: false, validateFormats: false })
  const validate = ajv.compile(schema)
  assert.equal(validate(value), true, `${schemaName}: ${JSON.stringify(validate.errors)}`)
}

async function main() {
  const dir = await latestAuditDir()
  const source = await readJson(resolve(dir, 'ftr6_source_manifest.json'))
  const gate = await readJson(resolve(dir, '14_release_gate_audit.json'))
  const manifest = await readJson(resolve(dir, 'formal_release_review_manifest.json'))
  const html = await readFile(resolve(dir, 'acceptance-report.html'), 'utf8')
  const summary = await readFile(resolve(dir, 'SUMMARY_FOR_GPT.md'), 'utf8')
  await Promise.all([
    validateSchema('ftr-6-source-manifest.schema.json', source),
    validateSchema('ftr-6-provisional-release-gate-audit.schema.json', gate),
    validateSchema('ftr-6-provisional-review-manifest.schema.json', manifest),
  ])
  assert.deepEqual(source.sourceStageCoverage, STAGES)
  assert.deepEqual(manifest.stageCoverage, STAGES)
  assert.equal(new Set(source.sourceArtifacts.map((artifact: any) => artifact.stageId)).size, STAGES.length)
  assert.equal(new Set(source.sourceArtifacts.map((artifact: any) => artifact.path)).size, source.sourceArtifacts.length)
  for (const artifact of source.sourceArtifacts) {
    const raw = await readFile(resolve(repoRoot, artifact.path))
    assert.equal(raw.byteLength, artifact.bytes, `source byte mismatch: ${artifact.path}`)
    assert.equal(sha256Bytes(raw), artifact.sha256, `source hash mismatch: ${artifact.path}`)
  }
  const sourceManifestRaw = await readFile(resolve(repoRoot, manifest.sourceManifest.path))
  assert.equal(sha256Bytes(sourceManifestRaw), manifest.sourceManifest.sha256)
  assert.deepEqual(manifest.sourceArtifacts, source.sourceArtifacts)
  for (const artifact of manifest.generatedArtifacts) {
    const raw = await readFile(resolve(dir, artifact.path))
    assert.equal(raw.byteLength, artifact.bytes, `generated byte mismatch: ${artifact.path}`)
    assert.equal(sha256Bytes(raw), artifact.sha256, `generated hash mismatch: ${artifact.path}`)
  }
  const queueArtifact = source.sourceArtifacts.find((artifact: any) => artifact.stageId === 'FTR-4' && artifact.name === 'deferred_human_review_queue.json')
  assert.ok(queueArtifact)
  assert.equal(queueArtifact.path, manifest.reviewQueue.path)
  assert.equal(queueArtifact.sha256, manifest.reviewQueue.sha256)
  const queue = await readJson(resolve(repoRoot, queueArtifact.path))
  assert.equal(queue.items.length, 8)
  assert.equal(queue.items.every((item: any) => item.status === 'pending' && item.reviewer === null && item.reviewedAt === null), true)
  const risk = queue.items.find((item: any) => item.reviewType === 'risk')
  assert.ok(risk)
  assert.equal(risk.sourceEvidenceStatus, 'automated_pass_human_pending')
  for (const name of ['13_execution_isolation_audit.json', 'trade_boundary_wording_audit.json', 'production_adapter_approval_record.json']) {
    assert.equal(risk.artifactRefs.some((path: string) => path.endsWith(name)), true, `risk evidence missing ${name}`)
  }
  const walkForwardArtifact = source.sourceArtifacts.find((artifact: any) => artifact.stageId === 'FTR-3' && artifact.name === 'walk_forward_replay.json')
  assert.ok(walkForwardArtifact)
  const walkForward = await readJson(resolve(repoRoot, walkForwardArtifact.path))
  const windows = walkForward.walkForward?.windows ?? walkForward.windows ?? []
  assert.ok(windows.some((window: any) => window.status === 'failed'), 'failed walk-forward window was hidden')
  assert.equal(gate.businessGates.manualSignoffPassed, false)
  assert.equal(gate.status, 'blocked')
  assert.equal(gate.engineeringPackageStatus, 'ready_for_human_review')
  assert.equal(manifest.reviewQueue.approvedCount, 0)
  assert.equal(manifest.reviewQueue.pendingCount, 8)
  assert.match(html, /当前架构与目标状态/)
  assert.match(html, /用户体验路径/)
  assert.match(html, /仍未完成与责任/)
  assert.match(html, /原始证据清单/)
  assert.match(html, /失败窗口保留/)
  assert.match(html, /formalTradingUnlocked=false/)
  assert.match(summary, /集中人工核查：pending_batch_review/)
  const combined = `${JSON.stringify(source)}\n${JSON.stringify(gate)}\n${JSON.stringify(manifest)}\n${html}\n${summary}`
  assert.doesNotMatch(combined, /"(formalTradingReleaseReady|productionAdapterEnabled|formalTradingUnlocked|autoTradeUnlocked|canCreateOrder|orderCreateAllowed)"\s*:\s*true/)
  console.log(JSON.stringify({
    schemaVersion: 'fams.formal_release.ftr6_provisional_package_verification.v1',
    status: 'passed',
    auditDir: dir,
    packageId: manifest.packageId,
    schemaValidationPassed: true,
    semanticValidationPassed: true,
    sourceArtifactCount: source.sourceArtifacts.length,
    sourceStageCoverage: STAGES,
    allArtifactHashesVerified: true,
    ftr4RiskEvidenceReboundToCurrentFtr5: true,
    failedWalkForwardWindowPreserved: true,
    humanAcceptanceStatus: 'pending_batch_review',
    batchHumanReviewReady: true,
    finalFormalReleaseReviewPackageReady: false,
    formalTradingReleaseReady: false,
    formalTradingUnlocked: false,
    autoTradeUnlocked: false,
    canCreateOrder: false,
    orderCreateAllowed: false,
  }, null, 2))
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
